Rscript script1_segmation_and_feature_extraction.R
Rscript script2_combine_features_and_pca.R
Rscript script3_random_forest_tuning.R
Rscript script4_random_forest_predictions.R
Rscript script6_other_images.R
